"""comentarios

Revision ID: c9992a839cc8
Revises: 450bd8f7d5fc
Create Date: 2026-07-24 17:37:55.318713

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "c9992a839cc8"
down_revision: str | None = "450bd8f7d5fc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comentarios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("solicitud_id", sa.Integer(), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column("texto", sa.Text(), nullable=False),
        sa.Column(
            "creado_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["solicitud_id"],
            ["solicitudes.id"],
            name=op.f("fk_comentarios_solicitud_id_solicitudes"),
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"], ["usuarios.id"], name=op.f("fk_comentarios_usuario_id_usuarios")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comentarios")),
    )
    op.create_index(
        "ix_comentarios_solicitud", "comentarios", ["solicitud_id", "creado_en"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_comentarios_solicitud", table_name="comentarios")
    op.drop_table("comentarios")
    # ### end Alembic commands ###
